### ISSUE TITLE
JWT security improvements

### ISSUE THREAD

**Issue by Piccirello** [danmoop/GitPals#8]
Noticed your own [post](https://www.gitpals.com/projects/GitPals) on GitPals (via HN) and figured I'd quickly audit your JWT implementation. This is not exhaustive but likely a good start:

1. A static, public secret is used for signing JWTs. This allows anyone to forge JWTs. You should instead generate a 256-bit pseudo-random value and inject that into your application via environment variables. Shameless plug: my company [Doppler](https://doppler.com/) is a fantastic secrets manager for this use case, but any will suffice.
https://github.com/danmoop/GitPals/blob/ceeba636912527008c7ffc00f5efd42b240b08c9/src/main/java/com/moople/gitpals/MainApplication/Configuration/JWTUtil.java#L17

2. Require user-submitted tokens to be signed with HS256. It appears you're properly signing issued tokens with HS256, but you may not be requiring this same signature algorithm when verifying the token. For example, can users provide a token with an algo of `none`?

https://github.com/danmoop/GitPals/blob/ceeba636912527008c7ffc00f5efd42b240b08c9/src/main/java/com/moople/gitpals/MainApplication/Configuration/JWTUtil.java#L33

3. Explicitly validate the JWT's signature before extracting data from it. It appears the username is parsed before the token is properly validated. (Edit: this may just be an issue of confusing naming)

https://github.com/danmoop/GitPals/blob/98155f59e571dcb1af44b50b81da2fb41354bb65/src/main/java/com/moople/gitpals/MainApplication/Configuration/JWTFilter.java#L35-L44

**Comment by danmoop** [comment]
JWT is really an important thing for a mobile app of GitPals & authorization. However, current JWT setup is actually not what I wrote myself, as instead, I just took a snippet of someone's code and made it kind of work for myself. 
I am afraid I don't even understand how to implement those started things you described. I hope this would be a great start for someone else who encounters this issue!

**Comment by Piccirello** [comment]
The first issue I highlighted is unfortunately a critical vulnerability. It is trivial for anyone to authenticate as any registered user. For example, anyone could create a JWT right now to gain access to your own user account.

I'd recommend reading up on JWTs if you're going to implement this yourself. jwt.io is a good starting point. If you don't want to deal with any of this, Auth0 would be another good option. They provide libraries that make it really easy to do user authentication securely.

**Comment by danmoop** [comment]
Currently, web version "gitpals.com" works by oauth, so thanks to Spring Security, you account is safe, however, JWT is for mobiles, so I will consider implementing the same oAuth into a mobile app, since it provides a lot of convenient things for a user and their security.

**Comment by danmoop** [comment]
I'm sticking with JWT for mobile phones authentication. Now, key is only known for the server, no user can view it. **(Data.java)** class contains it.
